/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Division */

#ifndef _Included_Division
#define _Included_Division
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Division
 * Method:    getDiv
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Division_getDiv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Division
 * Method:    ByteOr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Division_ByteOr
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
